version: 3

tasks:
  typecheck:
    run: once
    cmd: bun tsc

  lint:
    run: once
    cmd: bun oxfmt . && bun oxlint src/

  test:unit:
    run: once
    cmd: bun test

  test:playwright:
    run: once
    cmd: bun playwright test

  check:
    deps:
      - typecheck
      - lint
      - test:unit
      - test:playwright
