version: 3

tasks:
  typecheck:
    run: once
    sources:
      - src/**/*
      - bun.lock
    cmd: bun tsc

  lint:
    run: once
    sources:
      - src/**/*
      - bun.lock
    cmd: bun oxfmt . && bun oxlint src/

  test:unit:
    run: once
    sources:
      - src/**/*
      - bun.lock
    cmd: bun test

  test:playwright:
    run: once
    sources:
      - src/**/*
      - package.json
      - playwright.config.ts
      - bun.lock
    cmds:
      - bun playwright install chromium webkit
      - bun playwright test

  build:
    run: once
    sources:
      - src/**/*
      - bun.lock
    cmd: bun vite build

  deploy:
    deps:
      - build
      - check
    cmd: bun wrangler pages deploy dist/ --branch master --commit-dirty=true
    sources:
      - dist/**/*
      - bun.lock

  check:
    deps:
      - typecheck
      - lint
      - test:unit
      - test:playwright

  dev: bun vite dev
